export type WorkspaceTemplateFile = {
  path: string
  contents: string
}

export function getTemplateFiles(templateKey: string): WorkspaceTemplateFile[] {
  if (templateKey !== 'next-app') {
    throw new Error(`Unsupported template ${templateKey}`)
  }

  return [
    {
      path: 'package.json',
      contents: JSON.stringify(
        {
          name: 'atoms-generated-app',
          private: true,
          scripts: {
            dev: 'next dev --hostname 0.0.0.0 --port 3000',
            build: 'next build',
            start: 'next start --hostname 0.0.0.0 --port 3000',
          },
          dependencies: {
            next: '^15.0.0',
            react: '^19.0.0',
            'react-dom': '^19.0.0',
          },
          devDependencies: {
            typescript: '^5.0.0',
            '@types/node': '^22.0.0',
            '@types/react': '^19.0.0',
            '@types/react-dom': '^19.0.0',
          },
        },
        null,
        2,
      ),
    },
    {
      path: 'tsconfig.json',
      contents: JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2020',
            lib: ['dom', 'dom.iterable', 'es2020'],
            allowJs: false,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: 'esnext',
            moduleResolution: 'bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: 'preserve',
            incremental: true,
            plugins: [{ name: 'next' }],
          },
          include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
          exclude: ['node_modules'],
        },
        null,
        2,
      ),
    },
    {
      path: 'next-env.d.ts',
      contents: `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is auto-generated by Next.js.\n`,
    },
    {
      path: 'next.config.ts',
      contents: 'import type { NextConfig } from "next"\n\nconst nextConfig: NextConfig = {}\n\nexport default nextConfig\n',
    },
    {
      path: 'app/layout.tsx',
      contents:
        'import "./globals.css"\nimport type { ReactNode } from "react"\n\nexport default function RootLayout({ children }: { children: ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  )\n}\n',
    },
    {
      path: 'app/globals.css',
      contents:
        ':root {\n  color-scheme: light;\n  font-family: "Helvetica Neue", Arial, sans-serif;\n  background: #f4f1ea;\n  color: #1e1a16;\n}\n\n* {\n  box-sizing: border-box;\n}\n\nbody {\n  margin: 0;\n  min-height: 100vh;\n  background: radial-gradient(circle at top, #fff8e7 0%, #f4f1ea 55%, #ece6da 100%);\n}\n\nmain {\n  min-height: 100vh;\n}\n',
    },
    {
      path: 'app/page.tsx',
      contents:
        'export default function Page() {\n  return (\n    <main style={{ display: "grid", placeItems: "center", padding: "48px" }}>\n      <section style={{ maxWidth: 720, background: "rgba(255,255,255,0.82)", border: "1px solid rgba(30,26,22,0.08)", borderRadius: 28, padding: 32, boxShadow: "0 24px 80px rgba(30,26,22,0.08)" }}>\n        <p style={{ margin: 0, letterSpacing: "0.14em", textTransform: "uppercase", fontSize: 12, color: "#7d5d43" }}>Atoms Starter</p>\n        <h1 style={{ margin: "12px 0 0", fontSize: 40, lineHeight: 1.05 }}>Your GPT-5.2 workspace is ready.</h1>\n        <p style={{ margin: "16px 0 0", fontSize: 16, lineHeight: 1.6, color: "#4f443a" }}>Ask Atoms to redesign this page, add interactions, or scaffold more routes. The workspace starts from a real Next.js template so the preview can run in WebContainer.</p>\n      </section>\n    </main>\n  )\n}\n',
    },
  ]
}
